version: "3"
services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    volumes:
      - ./web/:/app
      - /app/node_modules
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge